---
title: "Final_report"
format: html
---

## PSM Model

The following output is the psm with the method= 'full matching'.

```{r, echo=FALSE, results='hide', message=FALSE}
library("MatchIt")
library("cobalt")    
library("ggplot2")   
library('dplyr')
library('lme4')

agg_data <- read.csv("final_tier2_with_surnames.csv", stringsAsFactors = FALSE)

library(dplyr)
agg_data <- agg_data %>%
  mutate(
    Name = as.character(Name),
    Gender = as.factor(Gender),
    Rank = as.numeric(Rank),         
    Journal_rank = as.factor(Journal_rank),
    Ethnicity = as.factor(Ethnicity),
    Surname_Initials = as.factor(Surname_Initials),
    tenure = as.factor(tenure),
    BA_to_PHD = as.numeric(BA_to_PHD),
    Econ_Index=as.factor(Econ_Index)
  ) 


agg_data$Rank_group <- cut(agg_data$Rank, 
                     breaks = c(0, 5, 15, 30, 50),
                     labels = c("Elite", "Leading","Strong","Good"))
agg_data$Rank_group<-as.factor(agg_data$Rank_group)

summary(agg_data)
psm <- matchit(Econ_Index ~ Journal_rank + Gender + Surname_Initials + Rank_group + Ethnicity + BA_to_PHD,
               data = agg_data, method='full', distance= 'logit', estimand='ATE') 


matched_data <- match.data(psm)

```



```{r, echo=TRUE}
model<- glm(
  tenure ~ Econ_Index,
  data    = matched_data,
  weights =weights,
  family  = binomial
)

summary(model)
```




```{r}
#| echo: True
model<- glm(
  tenure ~ Econ_Index + Gender + Ethnicity + BA_to_PHD,
  data    = matched_data,
  weights =weights,
  family  = binomial
)

summary(model)
```



```{r}
#| echo: True
model<- glm(
  tenure ~ Econ_Index + Gender + Ethnicity + BA_to_PHD+ Journal_rank,
  data    = matched_data,
  weights =weights,
  family  = binomial
)

summary(model)
```




```{r}
#| echo: True
model<- glm(
  tenure ~ Econ_Index + Gender + Ethnicity + BA_to_PHD+ Journal_rank+ Surname_Initials,
  data    = matched_data,
  weights =weights,
  family  = binomial
)

summary(model)

```



```{r}
#| echo: True
model<- glm(
  tenure ~ Econ_Index + Gender + Ethnicity + BA_to_PHD+ Journal_rank+ Surname_Initials + Rank_group,
  data    = matched_data,
  weights =weights,
  family  = binomial
)

summary(model)
```
